version: "3"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.24.0
    container_name: jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      apisix:

  consul:
    image: consul:1.10.2
    restart: always
    ports:
      - 8500:8500
      - 8300:8300
      - 8301:8301
      - 8302:8302
      - 8600:8600
    volumes:
      - ./consul/data:/consul/data
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
